

POST http://localhost:3055/v1/api/shop/handleRefreshToken
Content-Type: application/json
x-api-key : 74d0204e809b6bad1d7be91e3aafac01a79a99f5660267a1df50ab935913ee3b6606c810341c003f99c4aa51ed585e7df65f95be2570f01d31f9d4ce4c32685c
x-client-id : 65b8ecf9dd4607118e148c1c
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI4ZWNmOWRkNDYwNzExOGUxNDhjMWMiLCJlbWFpbCI6InR0aHBzcGt0QGdtYWlsLmNvbSIsImlhdCI6MTcwNjcwMzUyMSwiZXhwIjoxNzA2ODc2MzIxfQ.0VevxGRUdgsuwR9dtLev1maA8K42TA2Z6oaBv7UuQHA

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NWI4ZWNmOWRkNDYwNzExOGUxNDhjMWMiLCJlbWFpbCI6InR0aHBzcGt0QGdtYWlsLmNvbSIsImlhdCI6MTcwNjcwMzUyMSwiZXhwIjoxNzA3MzA4MzIxfQ.OhYFUGu19FUdPwky-iDuuFzHMUPS_PLIa8ySvytee_Q"
}
